name: Build KSA Tweak

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: true

      - name: Prepare Theos
        uses: Randomblock1/theos-action@v1

      - name: Build package
        run: |
          make package FINALPACKAGE=1
        
      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          name: KSA-Tweak-Deb
          path: packages/*.deb
