name: Makefile CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Setup Theos
      run: |
        mkdir -p /opt/theos
        git clone --recursive https://github.com/theos/theos.git /opt/theos
        /opt/theos/bin/update-theos
      env:
        THEOS: /opt/theos

    - name: Download iOS SDK
      run: |
        mkdir -p /opt/theos/sdks
        curl -L https://github.com/theos/sdks/releases/download/latest/iPhoneOS13.sdk.tar.gz -o iPhoneOS13.sdk.tar.gz
        tar -xzf iPhoneOS13.sdk.tar.gz -C /opt/theos/sdks/
        rm iPhoneOS13.sdk.tar.gz
      env:
        THEOS: /opt/theos

    - name: Build Tweak
      run: make package
      env:
        THEOS: /opt/theos

    - name: Upload artifacts
      if: success()
      uses: actions/upload-artifact@v4
      with:
        name: ksa-package
        path: packages/
